### ISSUE TITLE
StaticQuery always get `Loading (StaticQuery)` instead result expected

### ISSUE THREAD

**Issue by ole3021** [tomphill/gatsbyprismic#1]
when i follow the course in udemy, i come accross this issue, and i tried to install this repo locally to figure out the cause, but i still get the same issue 

![image](https://user-images.githubusercontent.com/2676686/85829033-3ccca280-b7bc-11ea-8fbd-c896696ffeb9.png)

my node v12.16.1

also i added this line in `package.json` to fix this [issue](https://github.com/birkir/gatsby-source-prismic-graphql/issues/217)

```
  "resolutions": {
    "gatsby-source-graphql-universal": "3.3.0"
  },
```

I tried to search on the internet, but still stuck with this issue. could you help have a check ? thanks.

**Comment by tomphill** [comment]
Hey @ole3021 - please see the updated lectures on udemy (specifically lecture 5). Thanks!

**Comment by michaelsmueller** [comment]
I am getting this same issue but in a different project. Could you please share the solution? Thanks!
